version: "3"
services:
  app:
    container_name: app.todo.com
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
    - MONGO_HOST=app.mongo.com


  mongo:
    container_name: app.mongo.com
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"